# Generated by Django 3.1.4 on 2021-01-02 06:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_auto_20210101_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user_like',
            field=models.ManyToManyField(blank=True, related_name='image_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
