'''
This file stores data for all the valid language, units and timezone provided by openwheathermap
'''

class resources():
    def __init__(self):
        self.lang_choice = [['af', 'Afrikaans'], ['al', 'Albanian'], ['ar', 'Arabic'], ['az', 'Azerbaijani'], ['bg', 'Bulgarian'], ['ca', 'Catalan'], ['cz', 'Czech'], ['da', 'Danish'], ['de', 'German'], ['el', 'Greek'], ['en', 'English'], ['eu', 'Basque'], ['fa', 'Persian (Farsi)'], ['fi', 'Finnish'], ['fr', 'French'], ['gl', 'Galician'], ['he', 'Hebrew'], ['hi', 'Hindi'], ['hr', 'Croatian'], ['hu', 'Hungarian'], ['id', 'Indonesian'], ['it', 'Italian'], ['ja', 'Japanese'], ['kr', 'Korean'], ['la', 'Latvian'], ['lt', 'Lithuanian'], ['mk', 'Macedonian'], ['no', 'Norwegian'], ['nl', 'Dutch'], ['pl', 'Polish'], ['pt', 'Portuguese'], ['pt_br', 'Português Brasil'], ['ro', 'Romanian'], ['ru', 'Russian'], ['sv', 'se Swedish'], ['sk', 'Slovak'], ['sl', 'Slovenian'], ['sp', 'es Spanish'], ['sr', 'Serbian'], ['th', 'Thai'], ['tr', 'Turkish'], ['ua', 'uk Ukrainian'], ['vi', 'Vietnamese'], ['zh_cn', 'Chinese Simplified'], ['zh_tw', 'Chinese Traditional'], ['zu', 'Zul']]

        self.unit_choice = [
            ('kelvin','Standard'),
            ('celsius','Metric'),
            ('farenheit','Imperial')
        ]

        self.timezone = [('ACDT', 'Australian Central Daylight Saving Time'),
                    ('ACST', 'Australian Central Standard Time'),
                    ('ACT', 'Acre Time'),
                    ('ACT', 'ASEAN Common Time'),
                    ('ACWST', 'Australian Central Western Standard Time'),
                    ('ADT', 'Atlantic Daylight Time'),
                    ('AEDT', 'Australian Eastern Daylight Saving Time'),
                    ('AEST', 'Australian Eastern Standard Time'),
                    ('AET', 'Australian Eastern Time'),
                    ('AFT', 'Afghanistan Time'),
                    ('AKDT', 'Alaska Daylight Time'),
                    ('AKST', 'Alaska Standard Time'),
                    ('AMST', 'Amazon Summer Time'),
                    ('AMT', 'Amazon Time'),
                    ('AMT', 'Armenia Time'),
                    ('ART', 'Argentina Time'),
                    ('AST', 'Arabia Standard Time'),
                    ('AST', 'Atlantic Standard Time'),
                    ('AWST', 'Australian Western Standard Time'),
                    ('AZOST', 'Azores Summer Time'),
                    ('AZOT', 'Azores Standard Time'),
                    ('AZT', 'Azerbaijan Time'),
                    ('BDT', 'Brunei Time'),
                    ('BIOT', 'British Indian Ocean Time'),
                    ('BIT', 'Baker Island Time'),
                    ('BOT', 'Bolivia Time'),
                    ('BRST', 'Brasília Summer Time'),
                    ('BRT', 'Brasília Time'),
                    ('BST', 'Bangladesh Standard Time'),
                    ('BST', 'Bougainville Standard Time'),
                    ('BST', 'British Summer Time'),
                    ('BTT', 'Bhutan Time'),
                    ('CAT', 'Central Africa Time'),
                    ('CCT', 'Cocos Islands Time'),
                    ('CDT', 'Central Daylight Time'),
                    ('CDT', 'Cuba Daylight Time'),
                    ('CEST', 'Central European Summer Time'),
                    ('CET', 'Central European Time'),
                    ('CHADT', 'Chatham Daylight Time'),
                    ('CHAST', 'Chatham Standard Time'),
                    ('CHOT', 'Choibalsan Standard Time'),
                    ('CHOST', 'Choibalsan Summer Time'),
                    ('CHST', 'Chamorro Standard Time'),
                    ('CHUT', 'Chuuk Time'),
                    ('CIST', 'Clipperton Island Standard Time'),
                    ('CIT', 'Central Indonesia Time'),
                    ('CKT', 'Cook Island Time'),
                    ('CLST', 'Chile Summer Time'),
                    ('CLT', 'Chile Standard Time'),
                    ('COST', 'Colombia Summer Time'),
                    ('COT', 'Colombia Time'),
                    ('CST', 'Central Standard Time'),
                    ('CST', 'China Standard Time'),
                    ('CST', 'Cuba Standard Time'),
                    ('CT', 'China Time'),
                    ('CVT', 'Cape Verde Time'),
                    ('CWST', 'Central Western Standard Time'),
                    ('CXT', 'Christmas Island Time'),
                    ('DAVT', 'Davis Time'),
                    ('DDUT', "Dumont d'Urville Time"),
                    ('EASST', 'Easter Island Summer Time'),
                    ('EAST', 'Easter Island Standard Time'),
                    ('EAT', 'East Africa Time'),
                    ('ECT', 'Eastern Caribbean Time'),
                    ('ECT', 'Ecuador Time'),
                    ('EDT', 'Eastern Daylight Time'),
                    ('EEST', 'Eastern European Summer Time'),
                    ('EET', 'Eastern European Time'),
                    ('EGST', 'Eastern Greenland Summer Time'),
                    ('EGT', 'Eastern Greenland Time'),
                    ('EIT', 'Eastern Indonesian Time'),
                    ('EST', 'Eastern Standard Time (North America)'),
                    ('FET', 'Further-eastern European Time'),
                    ('FJT', 'Fiji Time'),
                    ('FKST', 'Falkland Islands Summer Time'),
                    ('FKT', 'Falkland Islands Time'),
                    ('FNT', 'Fernando de Noronha Time'),
                    ('GALT', 'Galápagos Time'),
                    ('GAMT', 'Gambier Islands Time'),
                    ('GET', 'Georgia Standard Time'),
                    ('GFT', 'French Guiana Time'),
                    ('GILT', 'Gilbert Island Time'),
                    ('GIT', 'Gambier Island Time'),
                    ('GMT', 'Greenwich Mean Time'),
                    ('GST', 'South Georgia and the South Sandwich Islands Time'),
                    ('GST', 'Gulf Standard Time'),
                    ('GYT', 'Guyana Time'),
                    ('HDT', 'Hawaii–Aleutian Daylight Time'),
                    ('HAEC', "Heure Avancée d'Europe Centrale"),
                    ('HST', 'Hawaii–Aleutian Standard Time'),
                    ('HKT', 'Hong Kong Time'),
                    ('HMT', 'Heard and McDonald Islands'),
                    ('HOVST', 'Hovd Summer Time'),
                    ('HOVT', 'Hovd Time'),
                    ('ICT', 'Indochina Time'),
                    ('IDLW', 'International Day Line West time zone'),
                    ('IDT', 'Israel Daylight Time'),
                    ('IOT', 'Indian Ocean Time'),
                    ('IRDT', 'Iran Daylight Time'),
                    ('IRKT', 'Irkutsk Time'),
                    ('IRST', 'Iran Standard Time'),
                    ('IST', 'Indian Standard Time'),
                    ('IST', 'Irish Standard Time'),
                    ('IST', 'Israel Standard Time'),
                    ('JST', 'Japan Standard Time'),
                    ('KALT', 'Kaliningrad Time'),
                    ('KGT', 'Kyrgyzstan Time'),
                    ('KOST', 'Kosrae Time'),
                    ('KRAT', 'Krasnoyarsk Time'),
                    ('KST', 'Korea Standard Time'),
                    ('LHST', 'Lord Howe Standard Time'),
                    ('LHST', 'Lord Howe Summer Time'),
                    ('LINT', 'Line Islands'),
                    ('MAGT', 'Magadan Time'),
                    ('MART', 'Marquesas Islands Time'),
                    ('MAWT', 'Mawson Station Time'),
                    ('MDT', 'Mountain Daylight Time'),
                    ('MET', 'Middle European Time'),
                    ('MEST', 'Middle European Summer Time'),
                    ('MHT', 'Marshall Islands Time'),
                    ('MIST', 'Macquarie Island Station Time'),
                    ('MIT', 'Marquesas Islands Time'),
                    ('MMT', 'Myanmar Standard Time'),
                    ('MSK', 'Moscow Time'),
                    ('MST', 'Malaysia Standard Time'),
                    ('MST', 'Mountain Standard Time'),
                    ('MUT', 'Mauritius Time'),
                    ('MVT', 'Maldives Time'),
                    ('MYT', 'Malaysia Time'),
                    ('NCT', 'New Caledonia Time'),
                    ('NDT', 'Newfoundland Daylight Time'),
                    ('NFT', 'Norfolk Island Time'),
                    ('NPT', 'Nepal Time'),
                    ('NST', 'Newfoundland Standard Time'),
                    ('NT', 'Newfoundland Time'),
                    ('NUT', 'Niue Time'),
                    ('NZDT', 'New Zealand Daylight Time'),
                    ('NZST', 'New Zealand Standard Time'),
                    ('OMST', 'Omsk Time'),
                    ('ORAT', 'Oral Time'),
                    ('PDT', 'Pacific Daylight Time'),
                    ('PET', 'Peru Time'),
                    ('PETT', 'Kamchatka Time'),
                    ('PGT', 'Papua New Guinea Time'),
                    ('PHOT', 'Phoenix Island Time'),
                    ('PHT', 'Philippine Time'),
                    ('PKT', 'Pakistan Standard Time'),
                    ('PMDT', 'Saint Pierre and Miquelon Daylight Time'),
                    ('PMST', 'Saint Pierre and Miquelon Standard Time'),
                    ('PONT', 'Pohnpei Standard Time'),
                    ('PST', 'Pacific Standard Time'),
                    ('PST', 'Philippine Standard Time'),
                    ('PYST', 'Paraguay Summer Time'),
                    ('PYT', 'Paraguay Time'),
                    ('RET', 'Réunion Time'),
                    ('ROTT', 'Rothera Research Station Time'),
                    ('SAKT', 'Sakhalin Island Time'),
                    ('SAMT', 'Samara Time'),
                    ('SAST', 'South African Standard Time'),
                    ('SBT', 'Solomon Islands Time'),
                    ('SCT', 'Seychelles Time'),
                    ('SDT', 'Samoa Daylight Time'),
                    ('SGT', 'Singapore Time'),
                    ('SLST', 'Sri Lanka Standard Time'),
                    ('SRET', 'Srednekolymsk Time'),
                    ('SRT', 'Suriname Time'),
                    ('SST', 'Samoa Standard Time'),
                    ('SST', 'Singapore Standard Time'),
                    ('SYOT', 'Showa Station Time'),
                    ('TAHT', 'Tahiti Time'),
                    ('THA', 'Thailand Standard Time'),
                    ('TJT', 'Tajikistan Time'),
                    ('TKT', 'Tokelau Time'),
                    ('TLT', 'Timor Leste Time'),
                    ('TMT', 'Turkmenistan Time'),
                    ('TRT', 'Turkey Time'),
                    ('TOT', 'Tonga Time'),
                    ('TVT', 'Tuvalu Time'),
                    ('ULAST', 'Ulaanbaatar Summer Time'),
                    ('ULAT', 'Ulaanbaatar Standard Time'),
                    ('UTC', 'Coordinated Universal Time'),
                    ('UYST', 'Uruguay Summer Time'),
                    ('UYT', 'Uruguay Standard Time'),
                    ('UZT', 'Uzbekistan Time'),
                    ('VET', 'Venezuelan Standard Time'),
                    ('VLAT', 'Vladivostok Time'),
                    ('VOLT', 'Volgograd Time'),
                    ('VOST', 'Vostok Station Time'),
                    ('VUT', 'Vanuatu'),
                    ('WAKT', 'Wake Island Time'),
                    ('WAST', 'West Africa Summer Time'),
                    ('WAT', 'West Africa Time'),
                    ('WEST', 'Western European Summer Time'),
                    ('WET', 'Western European Time'),
                    ('WIT', 'Western Indonesian Time'),
                    ('WST', 'Western Standard Time'),
                    ('YAKT', 'Yakutsk Time'),
                    ('YEKT', 'Yekaterinburg Time')]
