# Generated by Django 3.0.6 on 2020-05-18 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='foreign_key',
            field=models.ForeignKey(default='no_user', on_delete=django.db.models.deletion.CASCADE, to='app.PersonDetails'),
            preserve_default=False,
        ),
    ]
