# Generated by Django 3.1.1 on 2020-11-07 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_auto_20201107_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='something',
            new_name='fkey',
        ),
    ]
